// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCw0rCOMyurSAwIE8ypSbuk-snVTnm8104',
    appId: '1:138830696039:web:b0e7fa2ce9a0075510cec2',
    messagingSenderId: '138830696039',
    projectId: 'fluxetudiant',
    authDomain: 'fluxetudiant.firebaseapp.com',
    storageBucket: 'fluxetudiant.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPmxRBUQcDzXqGaTudx--1N6xLjp1n5WQ',
    appId: '1:138830696039:android:7eca3bfb90d65a1010cec2',
    messagingSenderId: '138830696039',
    projectId: 'fluxetudiant',
    storageBucket: 'fluxetudiant.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAr_r28nxBZrb8QBKS2AAJ-WVhuZnD3B0',
    appId: '1:138830696039:ios:0e6d02240310decb10cec2',
    messagingSenderId: '138830696039',
    projectId: 'fluxetudiant',
    storageBucket: 'fluxetudiant.firebasestorage.app',
    androidClientId: '138830696039-j62pcefkt7irpofomhc6k2e89n0m7aq5.apps.googleusercontent.com',
    iosClientId: '138830696039-hi486049vacsddcuq5lfu9611ag8omaj.apps.googleusercontent.com',
    iosBundleId: 'com.nthiekamw.madbeauty',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAr_r28nxBZrb8QBKS2AAJ-WVhuZnD3B0',
    appId: '1:138830696039:ios:0e6d02240310decb10cec2',
    messagingSenderId: '138830696039',
    projectId: 'fluxetudiant',
    storageBucket: 'fluxetudiant.firebasestorage.app',
    iosClientId:
        '138830696039-hi486049vacsddcuq5lfu9611ag8omaj.apps.googleusercontent.com',
    iosBundleId: 'com.nthiekamw.madbeauty',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCw0rCOMyurSAwIE8ypSbuk-snVTnm8104',
    appId: '1:138830696039:web:356c55a4597e081210cec2',
    messagingSenderId: '138830696039',
    projectId: 'fluxetudiant',
    authDomain: 'fluxetudiant.firebaseapp.com',
    storageBucket: 'fluxetudiant.firebasestorage.app',
  );
}
